ci: run scan on pr (#55)
* ci: run scan on pr

* ci: remove job execution on macos

We don't expect people running the GH Action on MacOS machines.
Even the concept of creating an OCI image exclusively for MacOS
doesn't make so much sense, the OCI images running on the Apple's OS
are mostly Linux images.

diff --git a/.github/workflows/ci-scan.yaml b/.github/workflows/ci-scan.yaml
--- a/.github/workflows/ci-scan.yaml
+++ b/.github/workflows/ci-scan.yaml
@@ -1,7 +1,7 @@
-name: Scan Image
+name: Scan Image on PR
 
 on:
-  workflow_dispatch:
+  pull_request:
 
 jobs:
   scan-from-registry:
@@ -15,6 +15,7 @@ jobs:
       - name: Scan dummy-vuln-app from registry
         id: scan
         uses: ./
+        continue-on-error: true
         with:
           # Tag of the image to analyse
           image-tag: sysdiglabs/dummy-vuln-app:latest
@@ -30,6 +31,15 @@ jobs:
         with:
           sarif_file: ${{ github.workspace }}/sarif.json
 
+      - name: Check that the scan has failed
+        run: |
+          if [ "${{ steps.scan.outcome }}" == "success" ]; then
+            echo "Scan succeeded but the step should fail."
+            exit 1
+          else
+            echo "Scan failed as expected."
+          fi
+
   filtered-scan-from-registry:
     runs-on: ubuntu-latest
 
@@ -41,6 +51,7 @@ jobs:
       - name: Scan dummy-vuln-app from registry
         id: scan
         uses: ./
+        continue-on-error: true
         with:
           # Tag of the image to analyse
           image-tag: sysdiglabs/dummy-vuln-app:latest
@@ -56,6 +67,15 @@ jobs:
         uses: github/codeql-action/upload-sarif@v3
         with:
           sarif_file: ${{ github.workspace }}/sarif.json
+
+      - name: Check that the scan has failed
+        run: |
+          if [ "${{ steps.scan.outcome }}" == "success" ]; then
+            echo "Scan succeeded but the step should fail."
+            exit 1
+          else
+            echo "Scan failed as expected."
+          fi
 
   standalone-scan-from-registry:
     runs-on: ubuntu-latest
@@ -94,3 +114,4 @@ jobs:
         uses: github/codeql-action/upload-sarif@v3
         with:
           sarif_file: ${{ github.workspace }}/sarif.json
+
