feat: update scanner version to 1.13.0

diff --git a/.github/workflows/ci-scan.yaml b/.github/workflows/ci-scan.yaml
--- a/.github/workflows/ci-scan.yaml
+++ b/.github/workflows/ci-scan.yaml
@@ -77,6 +77,44 @@ jobs:
             echo "Scan failed as expected."
           fi
 
+  scan-with-old-scanner-version:
+    runs-on: ubuntu-latest
+
+    steps:
+      # This step checks out a copy of your repository.
+      - name: Check out repository
+        uses: actions/checkout@v4
+
+      - name: Scan dummy-vuln-app from registry
+        id: scan
+        uses: ./
+        continue-on-error: true
+        with:
+          # Old scanner version
+          cli-scanner-version: 1.8.1
+          # Tag of the image to analyse
+          image-tag: sysdiglabs/dummy-vuln-app:latest
+          # API token for Sysdig Scanning auth
+          sysdig-secure-token: ${{ secrets.KUBELAB_SECURE_API_TOKEN }}
+          stop-on-failed-policy-eval: true
+          stop-on-processing-error: true
+          severity-at-least: medium
+
+      - name: Upload SARIF file
+        if: success() || failure() # Upload results regardless previous step fails
+        uses: github/codeql-action/upload-sarif@v3
+        with:
+          sarif_file: ${{ github.workspace }}/sarif.json
+
+      - name: Check that the scan has failed
+        run: |
+          if [ "${{ steps.scan.outcome }}" == "success" ]; then
+            echo "Scan succeeded but the step should fail."
+            exit 1
+          else
+            echo "Scan failed as expected."
+          fi
+
   standalone-scan-from-registry:
     runs-on: ubuntu-latest
 
