fix: allow use of space in policies  (#81)

diff --git a/.github/workflows/ci-scan.yaml b/.github/workflows/ci-scan.yaml
--- a/.github/workflows/ci-scan.yaml
+++ b/.github/workflows/ci-scan.yaml
@@ -153,3 +153,30 @@ jobs:
         with:
           sarif_file: ${{ github.workspace }}/sarif.json
 
+  scan-with-multiple-policies:
+    runs-on: ubuntu-latest
+
+    steps:
+      # This step checks out a copy of your repository.
+      - name: Check out repository
+        uses: actions/checkout@v4
+
+      - name: Scan repository with multiple IaC policies
+        id: scan
+        uses: ./
+        continue-on-error: true
+        with:
+          sysdig-secure-token: ${{ secrets.KUBELAB_SECURE_API_TOKEN }}
+          mode: iac
+          # Note: This test assumes these policies exist in the target Sysdig Secure account.
+          use-policies: '"All Posture Findings", "MITRE DEFEND"'
+
+      - name: Check that the scan has succeeded
+        run: |
+          if [ "${{ steps.scan.outcome }}" == "success" ]; then
+            echo "Scan succeeded as expected."
+          else
+            echo "Scan failed but it should have succeeded."
+            exit 1
+          fi
+
